# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8923f2d679dc4e73a282b7d528b87cac7e5bc51acc1453c4e3d77e57f869be7c2a3c59e76cda86b3555cafd9cd60bf6b6f22fa43f72aef7cb284156eb97f72ae

test:
  secret_key_base: 2b163c58a83f2e3359929d1159122600447e16c3894029513917381d6f9cc68a86dfb29e1f58238b54ed69b659c329489748b155c418b44073102a62f09d0988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
